version: "3.3"
services:
  ss-client:
    depends_on:
      - provixy
    image: shadowsocks/shadowsocks-libev:v3.3.5
    command:
      ss-local -s 8.210.213.197
      -p 8388
      -m aes-256-gcm
      -k 9MLSpPmNt
      -b 0.0.0.0
      -l 1080
      -t 60
      --fast-open
    restart: always
    network_mode: host
  provixy:
    image: caligari/privoxy:latest
    network_mode: host
    restart: always